<?php

namespace ContainerMiGp3T5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SD3KhdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SD_3Khd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SD_3Khd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\StationController::add' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\StationController::delete' => ['privates', '.service_locator.LUZGmvf', 'get_ServiceLocator_LUZGmvfService', true],
            'App\\Controller\\StationController::getAll' => ['privates', '.service_locator.4AVwkil', 'get_ServiceLocator_4AVwkilService', true],
            'App\\Controller\\StationController::update' => ['privates', '.service_locator.5K265bC', 'get_ServiceLocator_5K265bCService', true],
            'App\\Controller\\TrotinetteController::add' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\TrotinetteController::delete' => ['privates', '.service_locator.C9lxIDZ', 'get_ServiceLocator_C9lxIDZService', true],
            'App\\Controller\\TrotinetteController::getAll' => ['privates', '.service_locator.HW1Z_xB', 'get_ServiceLocator_HW1ZXBService', true],
            'App\\Controller\\TrotinetteController::update' => ['privates', '.service_locator.5cuDn.k', 'get_ServiceLocator_5cuDn_KService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\StationController:add' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\StationController:delete' => ['privates', '.service_locator.LUZGmvf', 'get_ServiceLocator_LUZGmvfService', true],
            'App\\Controller\\StationController:getAll' => ['privates', '.service_locator.4AVwkil', 'get_ServiceLocator_4AVwkilService', true],
            'App\\Controller\\StationController:update' => ['privates', '.service_locator.5K265bC', 'get_ServiceLocator_5K265bCService', true],
            'App\\Controller\\TrotinetteController:add' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\TrotinetteController:delete' => ['privates', '.service_locator.C9lxIDZ', 'get_ServiceLocator_C9lxIDZService', true],
            'App\\Controller\\TrotinetteController:getAll' => ['privates', '.service_locator.HW1Z_xB', 'get_ServiceLocator_HW1ZXBService', true],
            'App\\Controller\\TrotinetteController:update' => ['privates', '.service_locator.5cuDn.k', 'get_ServiceLocator_5cuDn_KService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\StationController::add' => '?',
            'App\\Controller\\StationController::delete' => '?',
            'App\\Controller\\StationController::getAll' => '?',
            'App\\Controller\\StationController::update' => '?',
            'App\\Controller\\TrotinetteController::add' => '?',
            'App\\Controller\\TrotinetteController::delete' => '?',
            'App\\Controller\\TrotinetteController::getAll' => '?',
            'App\\Controller\\TrotinetteController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\StationController:add' => '?',
            'App\\Controller\\StationController:delete' => '?',
            'App\\Controller\\StationController:getAll' => '?',
            'App\\Controller\\StationController:update' => '?',
            'App\\Controller\\TrotinetteController:add' => '?',
            'App\\Controller\\TrotinetteController:delete' => '?',
            'App\\Controller\\TrotinetteController:getAll' => '?',
            'App\\Controller\\TrotinetteController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
