<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6sGlDkQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6sGlDkQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6sGlDkQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6sGlDkQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6sGlDkQ\App_KernelDevDebugContainer([
    'container.build_hash' => '6sGlDkQ',
    'container.build_id' => '79ada053',
    'container.build_time' => 1713395322,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6sGlDkQ');
