<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_home' => [[], ['_controller' => 'App\\Controller\\FrontController::index'], [], [['text', '/front']], [], [], []],
    'app_station' => [[], ['_controller' => 'App\\Controller\\StationController::index'], [], [['text', '/base']], [], [], []],
    'app_gets' => [[], ['_controller' => 'App\\Controller\\StationController::getAll'], [], [['text', '/gets']], [], [], []],
    'station_add' => [[], ['_controller' => 'App\\Controller\\StationController::add'], [], [['text', '/station']], [], [], []],
    'station_update' => [['id'], ['_controller' => 'App\\Controller\\StationController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/updatee']], [], [], []],
    'deleteS' => [['id'], ['_controller' => 'App\\Controller\\StationController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/deletee']], [], [], []],
    'app_trotinette' => [[], ['_controller' => 'App\\Controller\\TrotinetteController::index'], [], [['text', '/base']], [], [], []],
    'app_getAll' => [[], ['_controller' => 'App\\Controller\\TrotinetteController::getAll'], [], [['text', '/getAll']], [], [], []],
    'trotinette_add' => [[], ['_controller' => 'App\\Controller\\TrotinetteController::add'], [], [['text', '/trotinette']], [], [], []],
    'trotinette_update' => [['id'], ['_controller' => 'App\\Controller\\TrotinetteController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/update']], [], [], []],
    'deleteT' => [['id'], ['_controller' => 'App\\Controller\\TrotinetteController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
