<?php

namespace ContainerHvuCxlx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CGXO4eyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cGXO4ey' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cGXO4ey'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'stationRepository' => ['privates', 'App\\Repository\\StationRepository', 'getStationRepositoryService', true],
            'trotinetteRepository' => ['privates', 'App\\Repository\\TrotinetteRepository', 'getTrotinetteRepositoryService', true],
            'validator' => ['services', '.container.private.validator', 'get_Container_Private_ValidatorService', false],
        ], [
            'entityManager' => '?',
            'stationRepository' => 'App\\Repository\\StationRepository',
            'trotinetteRepository' => 'App\\Repository\\TrotinetteRepository',
            'validator' => '?',
        ]);
    }
}
