<?php

namespace ContainerHvuCxlx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5K265bCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5K265bC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5K265bC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\StationRepository', 'getStationRepositoryService', true],
        ], [
            'entityManager' => '?',
            'repo' => 'App\\Repository\\StationRepository',
        ]);
    }
}
