<?php

namespace Container91Lx3r9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UK498EgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uK498Eg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uK498Eg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'excelController' => ['privates', 'App\\Controller\\ExcelController', 'getExcelControllerService', true],
        ], [
            'excelController' => 'App\\Controller\\ExcelController',
        ]);
    }
}
