<?php

namespace Container91Lx3r9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcelControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Controller\ExcelController' shared autowired service.
     *
     * @return \App\Controller\ExcelController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ExcelController.php';

        return $container->privates['App\\Controller\\ExcelController'] = new \App\Controller\ExcelController(($container->privates['App\\Repository\\TrotinetteRepository'] ?? $container->load('getTrotinetteRepositoryService')));
    }
}
